# Generated by Django 6.1 on 2026-08-19 23:26

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import hoard.campaigns.models.core


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("use_shared_exp", models.BooleanField(default=True)),
                ("shared_experience", models.PositiveIntegerField(default=0)),
                (
                    "item_sources",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[("5e", "D&D 5e"), ("5e2024", "D&D 5e (2024)")],
                            max_length=10,
                        ),
                        default=hoard.campaigns.models.core.default_item_sources,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CampaignContext",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("gm", "Game master"), ("pc", "Player character")],
                        max_length=2,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contexts",
                        to="campaigns.campaign",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campaign_contexts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Character",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=False)),
                ("is_archived", models.BooleanField(default=False)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=200)),
                ("race", models.CharField(max_length=100)),
                ("character_class", models.CharField(max_length=100)),
                ("strength", models.PositiveSmallIntegerField()),
                ("dexterity", models.PositiveSmallIntegerField()),
                ("constitution", models.PositiveSmallIntegerField()),
                ("intelligence", models.PositiveSmallIntegerField()),
                ("wisdom", models.PositiveSmallIntegerField()),
                ("charisma", models.PositiveSmallIntegerField()),
                ("base_hp", models.PositiveSmallIntegerField(default=1)),
                ("proficiency_bonus_adjustment", models.SmallIntegerField(default=0)),
                ("strength_modifier_adjustment", models.SmallIntegerField(default=0)),
                ("dexterity_modifier_adjustment", models.SmallIntegerField(default=0)),
                (
                    "constitution_modifier_adjustment",
                    models.SmallIntegerField(default=0),
                ),
                (
                    "intelligence_modifier_adjustment",
                    models.SmallIntegerField(default=0),
                ),
                ("wisdom_modifier_adjustment", models.SmallIntegerField(default=0)),
                ("charisma_modifier_adjustment", models.SmallIntegerField(default=0)),
                ("strength_save_proficient", models.BooleanField(default=False)),
                ("dexterity_save_proficient", models.BooleanField(default=False)),
                ("constitution_save_proficient", models.BooleanField(default=False)),
                ("intelligence_save_proficient", models.BooleanField(default=False)),
                ("wisdom_save_proficient", models.BooleanField(default=False)),
                ("charisma_save_proficient", models.BooleanField(default=False)),
                ("strength_save_adjustment", models.SmallIntegerField(default=0)),
                ("dexterity_save_adjustment", models.SmallIntegerField(default=0)),
                ("constitution_save_adjustment", models.SmallIntegerField(default=0)),
                ("intelligence_save_adjustment", models.SmallIntegerField(default=0)),
                ("wisdom_save_adjustment", models.SmallIntegerField(default=0)),
                ("charisma_save_adjustment", models.SmallIntegerField(default=0)),
                ("skill_proficiencies", models.JSONField(blank=True, default=dict)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="characters",
                        to="campaigns.campaign",
                    ),
                ),
                (
                    "context",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="character",
                        to="campaigns.campaigncontext",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExperienceAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_system", models.BooleanField(default=False)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="experience_accounts",
                        to="campaigns.campaign",
                    ),
                ),
                (
                    "character",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="experience_ledger_account",
                        to="campaigns.character",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExperienceTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("shared_award", "Shared award"),
                            ("baseline", "Activation baseline"),
                            ("reversal", "Reversal"),
                        ],
                        max_length=20,
                    ),
                ),
                ("requested_amount", models.PositiveIntegerField(default=0)),
                ("discarded_amount", models.PositiveIntegerField(default=0)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="campaigns.campaign",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="campaigns.campaigncontext",
                    ),
                ),
                (
                    "reversal_of",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reversal",
                        to="campaigns.experiencetransaction",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ExperienceEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.IntegerField()),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entries",
                        to="campaigns.experienceaccount",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entries",
                        to="campaigns.experiencetransaction",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InventoryAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_system", models.BooleanField(default=False)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_accounts",
                        to="campaigns.campaign",
                    ),
                ),
                (
                    "character",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_ledger_account",
                        to="campaigns.character",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InventoryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("source_repository", models.URLField(blank=True)),
                ("source_system", models.CharField(blank=True, max_length=100)),
                ("source_book", models.CharField(blank=True, max_length=100)),
                ("equipment_category", models.CharField(blank=True, max_length=20)),
                ("item_type", models.CharField(blank=True, max_length=100)),
                ("source_identifier", models.CharField(blank=True, max_length=200)),
                (
                    "cost_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("cost_currency", models.CharField(blank=True, max_length=3)),
                (
                    "weight_amount",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
                ("weight_unit", models.CharField(blank=True, max_length=20)),
                ("rarity", models.CharField(blank=True, max_length=50)),
                ("is_magic", models.BooleanField(blank=True, null=True)),
                ("requires_attunement", models.BooleanField(blank=True, null=True)),
                ("source_data", models.JSONField(blank=True, default=dict)),
                (
                    "campaign",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_items",
                        to="campaigns.campaign",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_inventory_items",
                        to="campaigns.campaigncontext",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InventoryTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="campaigns.campaign",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="campaigns.campaigncontext",
                    ),
                ),
                (
                    "reversal_of",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reversal",
                        to="campaigns.inventorytransaction",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="InventoryEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.IntegerField()),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entries",
                        to="campaigns.inventoryaccount",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entries",
                        to="campaigns.inventoryitem",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entries",
                        to="campaigns.inventorytransaction",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MoneyAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_system", models.BooleanField(default=False)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="money_accounts",
                        to="campaigns.campaign",
                    ),
                ),
                (
                    "character",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="money_ledger_account",
                        to="campaigns.character",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MoneyTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="campaigns.campaign",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="campaigns.campaigncontext",
                    ),
                ),
                (
                    "reversal_of",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reversal",
                        to="campaigns.moneytransaction",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MoneyEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.IntegerField()),
                (
                    "denomination",
                    models.CharField(
                        choices=[
                            ("cp", "Copper"),
                            ("sp", "Silver"),
                            ("ep", "Electrum"),
                            ("gp", "Gold"),
                            ("pp", "Platinum"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entries",
                        to="campaigns.moneyaccount",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entries",
                        to="campaigns.moneytransaction",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="campaigncontext",
            constraint=models.UniqueConstraint(
                fields=("campaign", "user", "kind"),
                name="unique_context_kind_per_user_per_campaign",
            ),
        ),
        migrations.AddConstraint(
            model_name="experienceaccount",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_system", True)),
                fields=("campaign",),
                name="one_system_experience_account_per_campaign",
            ),
        ),
        migrations.AddConstraint(
            model_name="experienceaccount",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("character__isnull", True), ("is_system", True)),
                    models.Q(("character__isnull", False), ("is_system", False)),
                    _connector="OR",
                ),
                name="experience_account_system_or_character",
            ),
        ),
        migrations.AddConstraint(
            model_name="experienceentry",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount", 0), _negated=True),
                name="experience_entry_nonzero_amount",
            ),
        ),
        migrations.AddConstraint(
            model_name="inventoryaccount",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_system", True)),
                fields=("campaign",),
                name="one_system_inventory_account_per_campaign",
            ),
        ),
        migrations.AddConstraint(
            model_name="inventoryaccount",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("character__isnull", True), ("is_system", True)),
                    models.Q(("character__isnull", False), ("is_system", False)),
                    _connector="OR",
                ),
                name="inventory_account_system_or_character",
            ),
        ),
        migrations.AddConstraint(
            model_name="inventoryitem",
            constraint=models.UniqueConstraint(
                condition=models.Q(("campaign__isnull", False)),
                fields=("campaign", "name"),
                name="unique_inventory_item_name_per_campaign",
            ),
        ),
        migrations.AddConstraint(
            model_name="inventoryitem",
            constraint=models.UniqueConstraint(
                condition=models.Q(("source_identifier__gt", "")),
                fields=(
                    "source_repository",
                    "source_system",
                    "equipment_category",
                    "source_identifier",
                ),
                name="unique_imported_equipment_source",
            ),
        ),
        migrations.AddConstraint(
            model_name="inventoryentry",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount", 0), _negated=True),
                name="inventory_entry_nonzero_amount",
            ),
        ),
        migrations.AddConstraint(
            model_name="moneyaccount",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_system", True)),
                fields=("campaign",),
                name="one_system_money_account_per_campaign",
            ),
        ),
        migrations.AddConstraint(
            model_name="moneyaccount",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("character__isnull", True), ("is_system", True)),
                    models.Q(("character__isnull", False), ("is_system", False)),
                    _connector="OR",
                ),
                name="money_account_system_or_character",
            ),
        ),
        migrations.AddConstraint(
            model_name="moneyentry",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount", 0), _negated=True),
                name="money_entry_nonzero_amount",
            ),
        ),
    ]
