# Generated by Django 6.1 on 2026-08-23 01:16

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "calendar_era_abbreviation",
                    models.CharField(default="PD", max_length=20),
                ),
                (
                    "calendar_era_name",
                    models.CharField(default="Powder Dynasty", max_length=100),
                ),
                ("calendar_year", models.PositiveIntegerField(default=81)),
                ("calendar_day", models.PositiveSmallIntegerField(default=137)),
                ("use_shared_exp", models.BooleanField(default=True)),
                ("shared_experience", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="CampaignContext",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("gm", "Game master"), ("pc", "Player character")],
                        max_length=2,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Character",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=False)),
                ("is_archived", models.BooleanField(default=False)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=200)),
                ("race", models.CharField(max_length=100)),
                ("character_class", models.CharField(max_length=100)),
                ("background", models.CharField(blank=True, max_length=100)),
                ("strength", models.PositiveSmallIntegerField()),
                ("dexterity", models.PositiveSmallIntegerField()),
                ("constitution", models.PositiveSmallIntegerField()),
                ("intelligence", models.PositiveSmallIntegerField()),
                ("wisdom", models.PositiveSmallIntegerField()),
                ("charisma", models.PositiveSmallIntegerField()),
                ("base_hp", models.PositiveSmallIntegerField(default=1)),
                ("current_hp", models.IntegerField(default=1)),
                ("temporary_hp", models.IntegerField(default=0)),
                ("base_ac", models.PositiveSmallIntegerField(default=10)),
                ("ac_adjustment", models.SmallIntegerField(default=0)),
                ("speed", models.CharField(blank=True, max_length=100)),
                ("spell_slots", models.JSONField(blank=True, default=dict)),
                ("proficiency_bonus_adjustment", models.SmallIntegerField(default=0)),
                ("strength_modifier_adjustment", models.SmallIntegerField(default=0)),
                ("dexterity_modifier_adjustment", models.SmallIntegerField(default=0)),
                (
                    "constitution_modifier_adjustment",
                    models.SmallIntegerField(default=0),
                ),
                (
                    "intelligence_modifier_adjustment",
                    models.SmallIntegerField(default=0),
                ),
                ("wisdom_modifier_adjustment", models.SmallIntegerField(default=0)),
                ("charisma_modifier_adjustment", models.SmallIntegerField(default=0)),
                ("strength_save_proficient", models.BooleanField(default=False)),
                ("dexterity_save_proficient", models.BooleanField(default=False)),
                ("constitution_save_proficient", models.BooleanField(default=False)),
                ("intelligence_save_proficient", models.BooleanField(default=False)),
                ("wisdom_save_proficient", models.BooleanField(default=False)),
                ("charisma_save_proficient", models.BooleanField(default=False)),
                ("strength_save_adjustment", models.SmallIntegerField(default=0)),
                ("dexterity_save_adjustment", models.SmallIntegerField(default=0)),
                ("constitution_save_adjustment", models.SmallIntegerField(default=0)),
                ("intelligence_save_adjustment", models.SmallIntegerField(default=0)),
                ("wisdom_save_adjustment", models.SmallIntegerField(default=0)),
                ("charisma_save_adjustment", models.SmallIntegerField(default=0)),
                ("skill_proficiencies", models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name="CharacterCompanion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("armor_class", models.PositiveSmallIntegerField(default=10)),
                ("max_hp", models.PositiveSmallIntegerField(default=1)),
                ("current_hp", models.IntegerField(default=1)),
                ("speed", models.CharField(blank=True, max_length=100)),
                ("abilities", models.JSONField(blank=True, default=dict)),
                ("attacks", models.JSONField(blank=True, default=list)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "ordering": ("name", "pk"),
            },
        ),
        migrations.CreateModel(
            name="CharacterFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("feat", "Feat"), ("feature", "Feature")],
                        default="feat",
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "ordering": ("name", "pk"),
            },
        ),
        migrations.CreateModel(
            name="CharacterLoadout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("equipped", models.BooleanField(default=False)),
                ("label", models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="CharacterNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200)),
                ("body", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ("pk",),
            },
        ),
        migrations.CreateModel(
            name="CharacterSpell",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("level", models.PositiveSmallIntegerField(default=0)),
                ("description", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("prepared", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ("level", "name", "pk"),
            },
        ),
        migrations.CreateModel(
            name="ExperienceAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_system", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="ExperienceEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="ExperienceTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("shared_award", "Shared award"),
                            ("baseline", "Activation baseline"),
                            ("reversal", "Reversal"),
                        ],
                        max_length=20,
                    ),
                ),
                ("requested_amount", models.PositiveIntegerField(default=0)),
                ("discarded_amount", models.PositiveIntegerField(default=0)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="InventoryAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_system", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="InventoryEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="InventoryTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MoneyAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_system", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="MoneyEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.IntegerField()),
                (
                    "denomination",
                    models.CharField(
                        choices=[
                            ("cp", "Copper"),
                            ("sp", "Silver"),
                            ("ep", "Electrum"),
                            ("gp", "Gold"),
                            ("pp", "Platinum"),
                        ],
                        max_length=2,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MoneyTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
