# Generated by Django 6.1 on 2026-08-18 20:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('use_shared_exp', models.BooleanField(default=True)),
                ('shared_experience', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=200)),
                ('race', models.CharField(max_length=100)),
                ('character_class', models.CharField(max_length=100)),
                ('strength', models.PositiveSmallIntegerField()),
                ('dexterity', models.PositiveSmallIntegerField()),
                ('constitution', models.PositiveSmallIntegerField()),
                ('intelligence', models.PositiveSmallIntegerField()),
                ('wisdom', models.PositiveSmallIntegerField()),
                ('charisma', models.PositiveSmallIntegerField()),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='campaigns.campaign')),
            ],
        ),
        migrations.CreateModel(
            name='ExperienceAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_system', models.BooleanField(default=False)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience_accounts', to='campaigns.campaign')),
                ('character', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experience_account', to='campaigns.character')),
            ],
        ),
        migrations.CreateModel(
            name='ExperienceTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(choices=[('shared_award', 'Shared award'), ('baseline', 'Activation baseline'), ('reversal', 'Reversal')], max_length=20)),
                ('requested_amount', models.PositiveIntegerField(default=0)),
                ('discarded_amount', models.PositiveIntegerField(default=0)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaigns.campaign')),
                ('reversal_of', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversal', to='campaigns.experiencetransaction')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExperienceEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='campaigns.experienceaccount')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='campaigns.experiencetransaction')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_system', models.BooleanField(default=False)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_accounts', to='campaigns.campaign')),
                ('character', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_account', to='campaigns.character')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='campaigns.campaign')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaigns.campaign')),
                ('reversal_of', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversal', to='campaigns.inventorytransaction')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InventoryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='campaigns.inventoryaccount')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='campaigns.inventoryitem')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='campaigns.inventorytransaction')),
            ],
        ),
        migrations.CreateModel(
            name='MoneyAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_system', models.BooleanField(default=False)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='money_accounts', to='campaigns.campaign')),
                ('character', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='money_account', to='campaigns.character')),
            ],
        ),
        migrations.CreateModel(
            name='MoneyTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaigns.campaign')),
                ('reversal_of', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversal', to='campaigns.moneytransaction')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MoneyEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('denomination', models.CharField(choices=[('cp', 'Copper'), ('sp', 'Silver'), ('ep', 'Electrum'), ('gp', 'Gold'), ('pp', 'Platinum')], max_length=2)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='campaigns.moneyaccount')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='campaigns.moneytransaction')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='campaigns.campaign')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_players', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='characters', to='campaigns.player'),
        ),
        migrations.AddConstraint(
            model_name='experienceaccount',
            constraint=models.UniqueConstraint(condition=models.Q(('is_system', True)), fields=('campaign',), name='one_system_experience_account_per_campaign'),
        ),
        migrations.AddConstraint(
            model_name='experienceaccount',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('character__isnull', True), ('is_system', True)), models.Q(('character__isnull', False), ('is_system', False)), _connector='OR'), name='experience_account_system_or_character'),
        ),
        migrations.AddConstraint(
            model_name='experienceentry',
            constraint=models.CheckConstraint(condition=models.Q(('amount', 0), _negated=True), name='experience_entry_nonzero_amount'),
        ),
        migrations.AddConstraint(
            model_name='inventoryaccount',
            constraint=models.UniqueConstraint(condition=models.Q(('is_system', True)), fields=('campaign',), name='one_system_inventory_account_per_campaign'),
        ),
        migrations.AddConstraint(
            model_name='inventoryaccount',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('character__isnull', True), ('is_system', True)), models.Q(('character__isnull', False), ('is_system', False)), _connector='OR'), name='inventory_account_system_or_character'),
        ),
        migrations.AddConstraint(
            model_name='inventoryitem',
            constraint=models.UniqueConstraint(fields=('campaign', 'name'), name='unique_inventory_item_name_per_campaign'),
        ),
        migrations.AddConstraint(
            model_name='inventoryentry',
            constraint=models.CheckConstraint(condition=models.Q(('amount', 0), _negated=True), name='inventory_entry_nonzero_amount'),
        ),
        migrations.AddConstraint(
            model_name='moneyaccount',
            constraint=models.UniqueConstraint(condition=models.Q(('is_system', True)), fields=('campaign',), name='one_system_money_account_per_campaign'),
        ),
        migrations.AddConstraint(
            model_name='moneyaccount',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('character__isnull', True), ('is_system', True)), models.Q(('character__isnull', False), ('is_system', False)), _connector='OR'), name='money_account_system_or_character'),
        ),
        migrations.AddConstraint(
            model_name='moneyentry',
            constraint=models.CheckConstraint(condition=models.Q(('amount', 0), _negated=True), name='money_entry_nonzero_amount'),
        ),
        migrations.AddConstraint(
            model_name='player',
            constraint=models.UniqueConstraint(fields=('campaign', 'user'), name='unique_player_per_campaign'),
        ),
        migrations.AddConstraint(
            model_name='character',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('player__isnull', False)), fields=('campaign', 'player'), name='one_active_character_per_player_per_campaign'),
        ),
    ]
