# Generated by Django 6.1 on 2026-08-18 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experienceaccount',
            name='character',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experience_ledger_account', to='campaigns.character'),
        ),
        migrations.AlterField(
            model_name='inventoryaccount',
            name='character',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_ledger_account', to='campaigns.character'),
        ),
        migrations.AlterField(
            model_name='moneyaccount',
            name='character',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='money_ledger_account', to='campaigns.character'),
        ),
    ]
