# Generated by Django 6.1 on 2026-09-16 21:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("campaigns", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="ability_bonuses",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="character",
            name="ability_score_adjustments",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="character",
            name="background_ability_bonuses",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="character",
            name="charisma",
            field=models.PositiveSmallIntegerField(default=10),
        ),
        migrations.AddField(
            model_name="character",
            name="constitution",
            field=models.PositiveSmallIntegerField(default=10),
        ),
        migrations.AddField(
            model_name="character",
            name="current_hp",
            field=models.PositiveIntegerField(default=1, verbose_name="Current HP"),
        ),
        migrations.AddField(
            model_name="character",
            name="dexterity",
            field=models.PositiveSmallIntegerField(default=10),
        ),
        migrations.AddField(
            model_name="character",
            name="hp_ability",
            field=models.CharField(default="constitution", max_length=20),
        ),
        migrations.AddField(
            model_name="character",
            name="hp_adjustment",
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="character",
            name="initiative_adjustment",
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="character",
            name="intelligence",
            field=models.PositiveSmallIntegerField(default=10),
        ),
        migrations.AddField(
            model_name="character",
            name="jack_of_all_trades",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="character",
            name="proficiency_bonus_adjustment",
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="character",
            name="remarkable_athlete",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="character",
            name="rolled_hit_points",
            field=models.PositiveIntegerField(
                default=1, verbose_name="Rolled Hit Points"
            ),
        ),
        migrations.AddField(
            model_name="character",
            name="save_adjustments",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="character",
            name="save_proficiencies",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="character",
            name="skill_adjustments",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="character",
            name="skill_proficiencies",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="character",
            name="strength",
            field=models.PositiveSmallIntegerField(default=10),
        ),
        migrations.AddField(
            model_name="character",
            name="temporary_hp",
            field=models.PositiveIntegerField(default=0, verbose_name="Temporary HP"),
        ),
        migrations.AddField(
            model_name="character",
            name="wisdom",
            field=models.PositiveSmallIntegerField(default=10),
        ),
        migrations.CreateModel(
            name="Encounter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="encounters",
                        to="campaigns.campaign",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EncounterCombatant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=200)),
                ("initiative", models.SmallIntegerField(default=0)),
                (
                    "initiative_roll",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("initiative_modifier", models.SmallIntegerField(default=0)),
                ("position", models.PositiveIntegerField(default=0)),
                ("current_hp", models.PositiveIntegerField(blank=True, null=True)),
                ("max_hp", models.PositiveIntegerField(blank=True, null=True)),
                ("show_hp_numbers", models.BooleanField(default=False)),
                (
                    "character",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="encounter_entries",
                        to="campaigns.character",
                    ),
                ),
                (
                    "encounter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="combatants",
                        to="campaigns.encounter",
                    ),
                ),
            ],
            options={
                "ordering": ("position", "pk"),
            },
        ),
        migrations.AddField(
            model_name="encounter",
            name="current_combatant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="campaigns.encountercombatant",
            ),
        ),
        migrations.AddConstraint(
            model_name="encounter",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("campaign",),
                name="one_active_encounter_per_campaign",
            ),
        ),
        migrations.CreateModel(
            name="HealthTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "occurred_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Occurred At",
                    ),
                ),
                (
                    "actor_username",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Actor Username"
                    ),
                ),
                (
                    "campaign_era_abbreviation",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Campaign Era Abbreviation",
                    ),
                ),
                (
                    "campaign_year",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Campaign Year"
                    ),
                ),
                (
                    "campaign_day",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Campaign Day"
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("damage", "Damage"),
                            ("healing", "Healing"),
                            ("temporary", "Temporary HP"),
                            ("correction", "Correction"),
                            ("short_rest", "Short rest"),
                            ("long_rest", "Long rest"),
                        ],
                        max_length=20,
                    ),
                ),
                ("current_hp_before", models.PositiveIntegerField()),
                ("current_hp_after", models.PositiveIntegerField()),
                ("temporary_hp_before", models.PositiveIntegerField()),
                ("temporary_hp_after", models.PositiveIntegerField()),
                ("description", models.TextField(blank=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="campaigns.campaign",
                        verbose_name="Campaign",
                    ),
                ),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="health_history",
                        to="campaigns.character",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="campaigns.campaigncontext",
                    ),
                ),
            ],
            options={
                "verbose_name": "Health Change",
                "verbose_name_plural": "Health Changes",
            },
        ),
    ]
