# Generated by Django 6.1 on 2026-08-23 13:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

XP_LEVEL_THRESHOLDS = (
    0,
    300,
    900,
    2700,
    6500,
    14000,
    23000,
    34000,
    48000,
    64000,
    85000,
    100000,
    120000,
    140000,
    165000,
    195000,
    225000,
    265000,
    305000,
    355000,
)


def initialise_progression_and_health(apps, schema_editor):
    Campaign = apps.get_model("campaigns", "Campaign")
    Character = apps.get_model("campaigns", "Character")
    CharacterClassLevel = apps.get_model("campaigns", "CharacterClassLevel")
    CharacterLevelProgress = apps.get_model("campaigns", "CharacterLevelProgress")
    HealthTransaction = apps.get_model("campaigns", "HealthTransaction")
    now = django.utils.timezone.now()
    for campaign in Campaign.objects.all():
        campaign.level = max(
            level
            for level, threshold in enumerate(XP_LEVEL_THRESHOLDS, start=1)
            if campaign.shared_experience >= threshold
        )
        campaign.save(update_fields=("level",))
        for character in Character.objects.filter(campaign=campaign):
            HealthTransaction.objects.create(
                campaign=campaign,
                character=character,
                occurred_at=now,
                campaign_era_abbreviation=campaign.calendar_era_abbreviation,
                campaign_year=campaign.calendar_year,
                campaign_day=campaign.calendar_day,
                reason="baseline",
                current_hp_delta=character.current_hp,
                temporary_hp_delta=character.temporary_hp,
                current_hp_before=0,
                current_hp_after=character.current_hp,
                temporary_hp_before=0,
                temporary_hp_after=character.temporary_hp,
                description="Opening health balance",
            )
            if character.context_id:
                CharacterClassLevel.objects.bulk_create(
                    [
                        CharacterClassLevel(
                            character=character,
                            level=level,
                            class_name=character.character_class,
                            is_override=True,
                        )
                        for level in range(1, campaign.level + 1)
                    ]
                )
                CharacterLevelProgress.objects.bulk_create(
                    [
                        CharacterLevelProgress(
                            character=character,
                            level=level,
                            is_complete=True,
                            completed_at=now,
                        )
                        for level in range(1, campaign.level + 1)
                    ]
                )


class Migration(migrations.Migration):
    dependencies = [
        ("campaigns", "0002_initial"),
        ("compendium", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="level",
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="character",
            name="ability_bonuses",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="character",
            name="ability_score_adjustments",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="character",
            name="about",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="character",
            name="alignment",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="character",
            name="background_entry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="background_characters",
                to="compendium.compendiumentry",
            ),
        ),
        migrations.AddField(
            model_name="character",
            name="bonds",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="character",
            name="equipment_proficiencies",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="character",
            name="flaws",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="character",
            name="hp_ability",
            field=models.CharField(default="constitution", max_length=20),
        ),
        migrations.AddField(
            model_name="character",
            name="hp_adjustment",
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="character",
            name="ideals",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="character",
            name="is_build_complete",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="character",
            name="languages",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="character",
            name="npc_level",
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="character",
            name="personality_traits",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="character",
            name="race_entry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="race_characters",
                to="compendium.compendiumentry",
            ),
        ),
        migrations.AddField(
            model_name="character",
            name="subrace_identifier",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="character",
            name="subrace_name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="experiencetransaction",
            name="campaign_day",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="experiencetransaction",
            name="campaign_era_abbreviation",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="experiencetransaction",
            name="campaign_year",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.RenameField(
            model_name="experiencetransaction",
            old_name="created_at",
            new_name="occurred_at",
        ),
        migrations.AlterField(
            model_name="experiencetransaction",
            name="occurred_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False
            ),
        ),
        migrations.AddField(
            model_name="inventorytransaction",
            name="campaign_day",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="inventorytransaction",
            name="campaign_era_abbreviation",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="inventorytransaction",
            name="campaign_year",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.RenameField(
            model_name="inventorytransaction",
            old_name="created_at",
            new_name="occurred_at",
        ),
        migrations.AlterField(
            model_name="inventorytransaction",
            name="occurred_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False
            ),
        ),
        migrations.AddField(
            model_name="moneytransaction",
            name="campaign_day",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="moneytransaction",
            name="campaign_era_abbreviation",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="moneytransaction",
            name="campaign_year",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.RenameField(
            model_name="moneytransaction",
            old_name="created_at",
            new_name="occurred_at",
        ),
        migrations.AlterField(
            model_name="moneytransaction",
            name="occurred_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False
            ),
        ),
        migrations.CreateModel(
            name="CalendarEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "occurred_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "campaign_era_abbreviation",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("campaign_year", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "campaign_day",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("before_era_abbreviation", models.CharField(max_length=20)),
                ("before_year", models.PositiveIntegerField()),
                ("before_day", models.PositiveSmallIntegerField()),
                ("after_era_abbreviation", models.CharField(max_length=20)),
                ("after_year", models.PositiveIntegerField()),
                ("after_day", models.PositiveSmallIntegerField()),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="campaigns.campaign",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="campaigns.campaigncontext",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CampaignInvitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token_digest", models.CharField(max_length=64, unique=True)),
                ("delivery_email", models.EmailField(blank=True, max_length=254)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "accepted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="accepted_campaign_invitations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitations",
                        to="campaigns.campaign",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_invitations",
                        to="campaigns.campaigncontext",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CampaignLevelEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "occurred_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "campaign_era_abbreviation",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("campaign_year", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "campaign_day",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("previous_level", models.PositiveSmallIntegerField()),
                ("next_level", models.PositiveSmallIntegerField()),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="campaigns.campaign",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="campaigns.campaigncontext",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CharacterHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "occurred_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "campaign_era_abbreviation",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("campaign_year", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "campaign_day",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("create", "Created"),
                            ("import", "Imported"),
                            ("edit", "Edited"),
                            ("override", "Override"),
                            ("level_up", "Level up"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("changes", models.JSONField(default=dict)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="campaigns.campaign",
                    ),
                ),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="history",
                        to="campaigns.character",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="campaigns.campaigncontext",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="HealthTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "occurred_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "campaign_era_abbreviation",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("campaign_year", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "campaign_day",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("baseline", "Baseline"),
                            ("damage", "Damage"),
                            ("healing", "Healing"),
                            ("temporary", "Temporary HP"),
                            ("correction", "Correction"),
                        ],
                        max_length=20,
                    ),
                ),
                ("current_hp_delta", models.IntegerField(default=0)),
                ("temporary_hp_delta", models.IntegerField(default=0)),
                ("current_hp_before", models.IntegerField()),
                ("current_hp_after", models.IntegerField()),
                ("temporary_hp_before", models.IntegerField()),
                ("temporary_hp_after", models.IntegerField()),
                ("description", models.TextField(blank=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="campaigns.campaign",
                    ),
                ),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="health_history",
                        to="campaigns.character",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="campaigns.campaigncontext",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="InvitationEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "occurred_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "campaign_era_abbreviation",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("campaign_year", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "campaign_day",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("resent", "Resent"),
                            ("revoked", "Revoked"),
                            ("accepted", "Accepted"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="campaigns.campaign",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="campaigns.campaigncontext",
                    ),
                ),
                (
                    "invitation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="events",
                        to="campaigns.campaigninvitation",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CharacterChoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("level", models.PositiveSmallIntegerField(default=1)),
                ("identifier", models.CharField(max_length=300)),
                ("kind", models.CharField(max_length=50)),
                ("values", models.JSONField(default=list)),
                ("is_override", models.BooleanField(default=False)),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="build_choices",
                        to="campaigns.character",
                    ),
                ),
                (
                    "origin_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="compendium.compendiumentry",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("character", "level", "identifier"),
                        name="unique_character_build_choice",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CharacterClassLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("level", models.PositiveSmallIntegerField()),
                ("class_name", models.CharField(max_length=200)),
                ("subclass_identifier", models.CharField(blank=True, max_length=200)),
                ("subclass_name", models.CharField(blank=True, max_length=200)),
                ("is_override", models.BooleanField(default=False)),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="class_levels",
                        to="campaigns.character",
                    ),
                ),
                (
                    "class_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="compendium.compendiumentry",
                    ),
                ),
            ],
            options={
                "ordering": ("level",),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("character", "level"),
                        name="unique_character_class_level",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CharacterLevelProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("level", models.PositiveSmallIntegerField()),
                ("is_complete", models.BooleanField(default=False)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="level_progress",
                        to="campaigns.character",
                    ),
                ),
            ],
            options={
                "ordering": ("level",),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("character", "level"),
                        name="unique_character_level_progress",
                    )
                ],
            },
        ),
        migrations.RunPython(
            initialise_progression_and_health, migrations.RunPython.noop
        ),
    ]
