# Generated by Django 6.1 on 2026-08-19

from django.db import migrations, models
import django.contrib.postgres.fields


class Migration(migrations.Migration):
    dependencies = [('campaigns', '0003_remove_inventoryitem_unique_inventory_item_name_per_campaign_and_more')]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='item_sources',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[('5e', 'D&D 5e'), ('5e2024', 'D&D 5e (2024)')],
                    max_length=10,
                ),
                default=['5e', '5e2024'],
                size=None,
            ),
        ),
    ]
