# Generated by Django 6.1 on 2026-08-23 13:54

from django.db import migrations, models


def attribute_opening_health(apps, schema_editor):
    health_transaction = apps.get_model("campaigns", "HealthTransaction")
    health_transaction.objects.filter(
        reason="baseline", created_by__isnull=True, actor_username=""
    ).update(actor_username="System")


class Migration(migrations.Migration):
    dependencies = [
        ("campaigns", "0004_membershipevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="calendarevent",
            name="actor_username",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="campaignlevelevent",
            name="actor_username",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="characterhistory",
            name="actor_username",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="experiencetransaction",
            name="actor_username",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="healthtransaction",
            name="actor_username",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="inventorytransaction",
            name="actor_username",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="invitationevent",
            name="actor_username",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="membershipevent",
            name="actor_username",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="moneytransaction",
            name="actor_username",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.RunPython(attribute_opening_health, migrations.RunPython.noop),
    ]
