# Generated by Django 6.1 on 2026-08-23 13:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("campaigns", "0005_calendarevent_actor_username_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="character",
            name="character_class",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="character",
            name="race",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
