# Generated by Django 6.1 on 2026-08-19

import django.contrib.postgres.fields
from django.db import migrations, models

import hoard.campaigns.models.core


class Migration(migrations.Migration):
    dependencies = [('campaigns', '0006_api_lifecycle_fields')]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='item_sources',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[('5e', 'D&D 5e'), ('5e2024', 'D&D 5e (2024)')],
                    max_length=10,
                ),
                default=hoard.campaigns.models.core.default_item_sources,
                size=None,
            ),
        ),
    ]
