# Generated by Django 6.1 on 2026-08-23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("campaigns", "0006_alter_character_character_class_alter_character_race")
    ]

    operations = [
        migrations.AddField(
            model_name="characterlevelprogress",
            name="hp_base_increase",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="characterlevelprogress",
            name="hp_method",
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
