# Generated by Django 6.1 on 2026-08-23 18:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("campaigns", "0007_characterlevelprogress_hp_method_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="campaignlevelevent",
            options={"verbose_name": "Level Up", "verbose_name_plural": "Level Ups"},
        ),
        migrations.AlterModelOptions(
            name="characterhistory",
            options={
                "verbose_name": "Character Modification",
                "verbose_name_plural": "Character Modifications",
            },
        ),
        migrations.AlterModelOptions(
            name="experiencetransaction",
            options={"verbose_name": "Experience", "verbose_name_plural": "Experience"},
        ),
        migrations.AlterModelOptions(
            name="healthtransaction",
            options={
                "verbose_name": "Health Change",
                "verbose_name_plural": "Health Changes",
            },
        ),
        migrations.AlterModelOptions(
            name="inventorytransaction",
            options={"verbose_name": "Inventory", "verbose_name_plural": "Inventory"},
        ),
        migrations.AlterModelOptions(
            name="invitationevent",
            options={
                "verbose_name": "Invitation Change",
                "verbose_name_plural": "Invitation Changes",
            },
        ),
        migrations.AlterModelOptions(
            name="membershipevent",
            options={
                "verbose_name": "Membership Change",
                "verbose_name_plural": "Membership Changes",
            },
        ),
        migrations.AlterModelOptions(
            name="moneytransaction",
            options={"verbose_name": "Coins", "verbose_name_plural": "Coins"},
        ),
        migrations.AlterField(
            model_name="campaign",
            name="calendar_day",
            field=models.PositiveSmallIntegerField(
                default=137, verbose_name="Calendar Day"
            ),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="calendar_era_abbreviation",
            field=models.CharField(
                default="PD", max_length=20, verbose_name="Calendar Era Abbreviation"
            ),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="calendar_era_name",
            field=models.CharField(
                default="Powder Dynasty",
                max_length=100,
                verbose_name="Calendar Era Name",
            ),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="calendar_year",
            field=models.PositiveIntegerField(default=81, verbose_name="Calendar Year"),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="level",
            field=models.PositiveSmallIntegerField(
                default=1, verbose_name="Campaign Level"
            ),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="name",
            field=models.CharField(max_length=200, verbose_name="Campaign Name"),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="shared_experience",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Shared Experience"
            ),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="use_shared_exp",
            field=models.BooleanField(
                default=True, verbose_name="Use Shared Experience"
            ),
        ),
        migrations.AlterField(
            model_name="campaignlevelevent",
            name="actor_username",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="Actor Username"
            ),
        ),
        migrations.AlterField(
            model_name="campaignlevelevent",
            name="campaign",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="campaigns.campaign",
                verbose_name="Campaign",
            ),
        ),
        migrations.AlterField(
            model_name="campaignlevelevent",
            name="campaign_day",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="Campaign Day"
            ),
        ),
        migrations.AlterField(
            model_name="campaignlevelevent",
            name="campaign_era_abbreviation",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                verbose_name="Campaign Era Abbreviation",
            ),
        ),
        migrations.AlterField(
            model_name="campaignlevelevent",
            name="campaign_year",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Campaign Year"
            ),
        ),
        migrations.AlterField(
            model_name="campaignlevelevent",
            name="occurred_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="Occurred At",
            ),
        ),
        migrations.AlterField(
            model_name="character",
            name="ability_bonuses",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="Ability Bonuses"
            ),
        ),
        migrations.AlterField(
            model_name="character",
            name="ability_score_adjustments",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="Ability Score Adjustments"
            ),
        ),
        migrations.AlterField(
            model_name="character",
            name="ac_adjustment",
            field=models.SmallIntegerField(default=0, verbose_name="AC Adjustment"),
        ),
        migrations.AlterField(
            model_name="character",
            name="archived_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Archived At"
            ),
        ),
        migrations.AlterField(
            model_name="character",
            name="base_ac",
            field=models.PositiveSmallIntegerField(default=10, verbose_name="Base AC"),
        ),
        migrations.AlterField(
            model_name="character",
            name="base_hp",
            field=models.PositiveSmallIntegerField(default=1, verbose_name="Base HP"),
        ),
        migrations.AlterField(
            model_name="character",
            name="character_class",
            field=models.CharField(blank=True, max_length=100, verbose_name="Class"),
        ),
        migrations.AlterField(
            model_name="character",
            name="charisma",
            field=models.PositiveSmallIntegerField(verbose_name="Charisma"),
        ),
        migrations.AlterField(
            model_name="character",
            name="constitution",
            field=models.PositiveSmallIntegerField(verbose_name="Constitution"),
        ),
        migrations.AlterField(
            model_name="character",
            name="current_hp",
            field=models.IntegerField(default=1, verbose_name="Current HP"),
        ),
        migrations.AlterField(
            model_name="character",
            name="dexterity",
            field=models.PositiveSmallIntegerField(verbose_name="Dexterity"),
        ),
        migrations.AlterField(
            model_name="character",
            name="equipment_proficiencies",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="Equipment Proficiencies"
            ),
        ),
        migrations.AlterField(
            model_name="character",
            name="hp_ability",
            field=models.CharField(
                default="constitution", max_length=20, verbose_name="HP Ability"
            ),
        ),
        migrations.AlterField(
            model_name="character",
            name="hp_adjustment",
            field=models.SmallIntegerField(default=0, verbose_name="HP Adjustment"),
        ),
        migrations.AlterField(
            model_name="character",
            name="intelligence",
            field=models.PositiveSmallIntegerField(verbose_name="Intelligence"),
        ),
        migrations.AlterField(
            model_name="character",
            name="is_active",
            field=models.BooleanField(default=False, verbose_name="Is Active"),
        ),
        migrations.AlterField(
            model_name="character",
            name="is_archived",
            field=models.BooleanField(default=False, verbose_name="Is Archived"),
        ),
        migrations.AlterField(
            model_name="character",
            name="is_build_complete",
            field=models.BooleanField(default=True, verbose_name="Is Build Complete"),
        ),
        migrations.AlterField(
            model_name="character",
            name="name",
            field=models.CharField(max_length=200, verbose_name="Character Name"),
        ),
        migrations.AlterField(
            model_name="character",
            name="personality_traits",
            field=models.TextField(blank=True, verbose_name="Personality Traits"),
        ),
        migrations.AlterField(
            model_name="character",
            name="proficiency_bonus_adjustment",
            field=models.SmallIntegerField(
                default=0, verbose_name="Proficiency Bonus Adjustment"
            ),
        ),
        migrations.AlterField(
            model_name="character",
            name="strength",
            field=models.PositiveSmallIntegerField(verbose_name="Strength"),
        ),
        migrations.AlterField(
            model_name="character",
            name="temporary_hp",
            field=models.IntegerField(default=0, verbose_name="Temporary HP"),
        ),
        migrations.AlterField(
            model_name="character",
            name="wisdom",
            field=models.PositiveSmallIntegerField(verbose_name="Wisdom"),
        ),
        migrations.AlterField(
            model_name="characterhistory",
            name="actor_username",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="Actor Username"
            ),
        ),
        migrations.AlterField(
            model_name="characterhistory",
            name="campaign",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="campaigns.campaign",
                verbose_name="Campaign",
            ),
        ),
        migrations.AlterField(
            model_name="characterhistory",
            name="campaign_day",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="Campaign Day"
            ),
        ),
        migrations.AlterField(
            model_name="characterhistory",
            name="campaign_era_abbreviation",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                verbose_name="Campaign Era Abbreviation",
            ),
        ),
        migrations.AlterField(
            model_name="characterhistory",
            name="campaign_year",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Campaign Year"
            ),
        ),
        migrations.AlterField(
            model_name="characterhistory",
            name="occurred_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="Occurred At",
            ),
        ),
        migrations.AlterField(
            model_name="experiencetransaction",
            name="actor_username",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="Actor Username"
            ),
        ),
        migrations.AlterField(
            model_name="experiencetransaction",
            name="campaign",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="campaigns.campaign",
                verbose_name="Campaign",
            ),
        ),
        migrations.AlterField(
            model_name="experiencetransaction",
            name="campaign_day",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="Campaign Day"
            ),
        ),
        migrations.AlterField(
            model_name="experiencetransaction",
            name="campaign_era_abbreviation",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                verbose_name="Campaign Era Abbreviation",
            ),
        ),
        migrations.AlterField(
            model_name="experiencetransaction",
            name="campaign_year",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Campaign Year"
            ),
        ),
        migrations.AlterField(
            model_name="experiencetransaction",
            name="description",
            field=models.TextField(blank=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="experiencetransaction",
            name="occurred_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="Occurred At",
            ),
        ),
        migrations.AlterField(
            model_name="healthtransaction",
            name="actor_username",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="Actor Username"
            ),
        ),
        migrations.AlterField(
            model_name="healthtransaction",
            name="campaign",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="campaigns.campaign",
                verbose_name="Campaign",
            ),
        ),
        migrations.AlterField(
            model_name="healthtransaction",
            name="campaign_day",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="Campaign Day"
            ),
        ),
        migrations.AlterField(
            model_name="healthtransaction",
            name="campaign_era_abbreviation",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                verbose_name="Campaign Era Abbreviation",
            ),
        ),
        migrations.AlterField(
            model_name="healthtransaction",
            name="campaign_year",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Campaign Year"
            ),
        ),
        migrations.AlterField(
            model_name="healthtransaction",
            name="occurred_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="Occurred At",
            ),
        ),
        migrations.AlterField(
            model_name="inventorytransaction",
            name="actor_username",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="Actor Username"
            ),
        ),
        migrations.AlterField(
            model_name="inventorytransaction",
            name="campaign",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="campaigns.campaign",
                verbose_name="Campaign",
            ),
        ),
        migrations.AlterField(
            model_name="inventorytransaction",
            name="campaign_day",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="Campaign Day"
            ),
        ),
        migrations.AlterField(
            model_name="inventorytransaction",
            name="campaign_era_abbreviation",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                verbose_name="Campaign Era Abbreviation",
            ),
        ),
        migrations.AlterField(
            model_name="inventorytransaction",
            name="campaign_year",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Campaign Year"
            ),
        ),
        migrations.AlterField(
            model_name="inventorytransaction",
            name="description",
            field=models.TextField(blank=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="inventorytransaction",
            name="occurred_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="Occurred At",
            ),
        ),
        migrations.AlterField(
            model_name="invitationevent",
            name="actor_username",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="Actor Username"
            ),
        ),
        migrations.AlterField(
            model_name="invitationevent",
            name="campaign",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="campaigns.campaign",
                verbose_name="Campaign",
            ),
        ),
        migrations.AlterField(
            model_name="invitationevent",
            name="campaign_day",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="Campaign Day"
            ),
        ),
        migrations.AlterField(
            model_name="invitationevent",
            name="campaign_era_abbreviation",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                verbose_name="Campaign Era Abbreviation",
            ),
        ),
        migrations.AlterField(
            model_name="invitationevent",
            name="campaign_year",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Campaign Year"
            ),
        ),
        migrations.AlterField(
            model_name="invitationevent",
            name="occurred_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="Occurred At",
            ),
        ),
        migrations.AlterField(
            model_name="membershipevent",
            name="actor_username",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="Actor Username"
            ),
        ),
        migrations.AlterField(
            model_name="membershipevent",
            name="campaign",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="campaigns.campaign",
                verbose_name="Campaign",
            ),
        ),
        migrations.AlterField(
            model_name="membershipevent",
            name="campaign_day",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="Campaign Day"
            ),
        ),
        migrations.AlterField(
            model_name="membershipevent",
            name="campaign_era_abbreviation",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                verbose_name="Campaign Era Abbreviation",
            ),
        ),
        migrations.AlterField(
            model_name="membershipevent",
            name="campaign_year",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Campaign Year"
            ),
        ),
        migrations.AlterField(
            model_name="membershipevent",
            name="occurred_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="Occurred At",
            ),
        ),
        migrations.AlterField(
            model_name="membershipevent",
            name="reason",
            field=models.CharField(
                choices=[("deactivated", "Deactivated")], max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="moneyentry",
            name="denomination",
            field=models.CharField(
                choices=[
                    ("cp", "Copper"),
                    ("sp", "Silver"),
                    ("ep", "Electrum"),
                    ("gp", "Gold"),
                    ("pp", "Platinum"),
                ],
                max_length=2,
                verbose_name="Denomination",
            ),
        ),
        migrations.AlterField(
            model_name="moneytransaction",
            name="actor_username",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="Actor Username"
            ),
        ),
        migrations.AlterField(
            model_name="moneytransaction",
            name="campaign",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="campaigns.campaign",
                verbose_name="Campaign",
            ),
        ),
        migrations.AlterField(
            model_name="moneytransaction",
            name="campaign_day",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="Campaign Day"
            ),
        ),
        migrations.AlterField(
            model_name="moneytransaction",
            name="campaign_era_abbreviation",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                verbose_name="Campaign Era Abbreviation",
            ),
        ),
        migrations.AlterField(
            model_name="moneytransaction",
            name="campaign_year",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Campaign Year"
            ),
        ),
        migrations.AlterField(
            model_name="moneytransaction",
            name="description",
            field=models.TextField(blank=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="moneytransaction",
            name="occurred_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="Occurred At",
            ),
        ),
        migrations.DeleteModel(
            name="CalendarEvent",
        ),
    ]
