# Generated by Django 6.1 on 2026-09-14 16:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("campaigns", "0011_campaigncontext_last_seen_at_character_portrait"),
        ("compendium", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Encounter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="encounters",
                        to="campaigns.campaign",
                    ),
                ),
                (
                    "started_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="started_encounters",
                        to="campaigns.campaigncontext",
                    ),
                ),
            ],
            options={
                "ordering": ("-started_at", "-pk"),
            },
        ),
        migrations.CreateModel(
            name="EncounterCombatant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=200)),
                ("initiative", models.SmallIntegerField(default=0)),
                ("current_hp", models.IntegerField(blank=True, null=True)),
                ("max_hp", models.PositiveIntegerField(blank=True, null=True)),
                ("show_hp_bar", models.BooleanField(default=False)),
                ("show_hp_numbers", models.BooleanField(default=False)),
                (
                    "character",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="encounter_entries",
                        to="campaigns.character",
                    ),
                ),
                (
                    "creature_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="encounter_combatants",
                        to="compendium.compendiumentry",
                    ),
                ),
                (
                    "encounter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="combatants",
                        to="campaigns.encounter",
                    ),
                ),
            ],
            options={
                "ordering": ("-initiative", "pk"),
            },
        ),
        migrations.CreateModel(
            name="ConditionEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "occurred_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Occurred At",
                    ),
                ),
                (
                    "actor_username",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Actor Username"
                    ),
                ),
                (
                    "campaign_era_abbreviation",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Campaign Era Abbreviation",
                    ),
                ),
                (
                    "campaign_year",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Campaign Year"
                    ),
                ),
                (
                    "campaign_day",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Campaign Day"
                    ),
                ),
                ("condition_instance_id", models.PositiveBigIntegerField()),
                ("target_name", models.CharField(max_length=200)),
                (
                    "identifier",
                    models.CharField(
                        choices=[
                            ("blinded", "Blinded"),
                            ("charmed", "Charmed"),
                            ("deafened", "Deafened"),
                            ("exhaustion", "Exhaustion"),
                            ("frightened", "Frightened"),
                            ("grappled", "Grappled"),
                            ("incapacitated", "Incapacitated"),
                            ("invisible", "Invisible"),
                            ("paralyzed", "Paralyzed"),
                            ("petrified", "Petrified"),
                            ("poisoned", "Poisoned"),
                            ("prone", "Prone"),
                            ("restrained", "Restrained"),
                            ("stunned", "Stunned"),
                            ("unconscious", "Unconscious"),
                            ("pacify", "Pacify"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("applied", "Applied"),
                            ("updated", "Updated"),
                            ("removed", "Removed"),
                        ],
                        max_length=20,
                    ),
                ),
                ("before", models.JSONField(blank=True, null=True)),
                ("after", models.JSONField(blank=True, null=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="campaigns.campaign",
                        verbose_name="Campaign",
                    ),
                ),
                (
                    "character",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="condition_history",
                        to="campaigns.character",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="campaigns.campaigncontext",
                    ),
                ),
                (
                    "encounter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="condition_events",
                        to="campaigns.encounter",
                    ),
                ),
                (
                    "combatant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="condition_events",
                        to="campaigns.encountercombatant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Condition Change",
                "verbose_name_plural": "Condition Changes",
                "ordering": ("-occurred_at", "-pk"),
            },
        ),
        migrations.CreateModel(
            name="CombatantCondition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "identifier",
                    models.CharField(
                        choices=[
                            ("blinded", "Blinded"),
                            ("charmed", "Charmed"),
                            ("deafened", "Deafened"),
                            ("exhaustion", "Exhaustion"),
                            ("frightened", "Frightened"),
                            ("grappled", "Grappled"),
                            ("incapacitated", "Incapacitated"),
                            ("invisible", "Invisible"),
                            ("paralyzed", "Paralyzed"),
                            ("petrified", "Petrified"),
                            ("poisoned", "Poisoned"),
                            ("prone", "Prone"),
                            ("restrained", "Restrained"),
                            ("stunned", "Stunned"),
                            ("unconscious", "Unconscious"),
                            ("pacify", "Pacify"),
                        ],
                        max_length=20,
                    ),
                ),
                ("source", models.CharField(blank=True, max_length=200)),
                ("duration", models.CharField(blank=True, max_length=200)),
                (
                    "exhaustion_level",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "combatant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conditions",
                        to="campaigns.encountercombatant",
                    ),
                ),
            ],
            options={
                "ordering": ("identifier", "pk"),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CharacterCondition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "identifier",
                    models.CharField(
                        choices=[
                            ("blinded", "Blinded"),
                            ("charmed", "Charmed"),
                            ("deafened", "Deafened"),
                            ("exhaustion", "Exhaustion"),
                            ("frightened", "Frightened"),
                            ("grappled", "Grappled"),
                            ("incapacitated", "Incapacitated"),
                            ("invisible", "Invisible"),
                            ("paralyzed", "Paralyzed"),
                            ("petrified", "Petrified"),
                            ("poisoned", "Poisoned"),
                            ("prone", "Prone"),
                            ("restrained", "Restrained"),
                            ("stunned", "Stunned"),
                            ("unconscious", "Unconscious"),
                            ("pacify", "Pacify"),
                        ],
                        max_length=20,
                    ),
                ),
                ("source", models.CharField(blank=True, max_length=200)),
                ("duration", models.CharField(blank=True, max_length=200)),
                (
                    "exhaustion_level",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conditions",
                        to="campaigns.character",
                    ),
                ),
            ],
            options={
                "ordering": ("identifier", "pk"),
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("identifier", "exhaustion")),
                        fields=("character", "identifier"),
                        name="one_exhaustion_condition_per_character",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="encounter",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("campaign",),
                name="one_active_encounter_per_campaign",
            ),
        ),
        migrations.AddConstraint(
            model_name="encountercombatant",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("current_hp__isnull", True),
                    ("current_hp__gte", 0),
                    _connector="OR",
                ),
                name="encounter_combatant_current_hp_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="combatantcondition",
            constraint=models.UniqueConstraint(
                condition=models.Q(("identifier", "exhaustion")),
                fields=("combatant", "identifier"),
                name="one_exhaustion_condition_per_combatant",
            ),
        ),
    ]
