# Generated by Django 6.1 on 2026-09-16 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0018_remove_encountercombatant_show_hp_bar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='use_shared_exp',
        ),
    ]
