# Generated by Django 6.1 on 2026-09-16 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0019_remove_campaign_use_shared_exp'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='kind',
            field=models.CharField(choices=[('pc', 'Player character'), ('npc', 'Non-player character')], default='pc', max_length=3),
        ),
    ]
