[project]
name = "Hoard"
version = "0.1.0"
description = "A D&D 5e tool for our campaign with specific tools for our homebrew rules. You won't be interested."
readme = "README.md"
authors = [
    { name = "Jay Turner", email = "jay@turnr.dev" }
]
requires-python = ">=3.14"
dependencies = [
    "django>=6.1",
    "django-vite>=3.1.0",
    "django-ninja>=1.5.3",
    "channels[daphne]>=4.2",
    "channels-redis>=4.2",
    "celery>=5.6",
    "psycopg[binary]>=3.3.4",
    "pydantic>=2.13.4",
]

[dependency-groups]
dev = [
    "django-stubs>=6.1.0",
    "ruff>=0.15.0",
]

[tool.django-stubs]
django_settings_module = "hoard.settings"

[tool.ruff]
extend-exclude = ["vendor"]

[tool.ruff.lint]
select = ["E", "F", "I"]
ignore = ["E501"]
