server {
    listen 80;
    server_name _;
    client_max_body_size 6m;

    location /static/ {
        alias /srv/static/;
        access_log off;
        expires 1y;
        add_header Cache-Control "public, immutable";
    }

    location /media/ {
        alias /srv/media/;
        access_log off;
        expires 1h;
    }

    location / {
        return 404;
    }
}
