"""Pydantic contracts shared by WebSocket and REST compatibility transports."""

from .calendar import (
    CalendarAdjustmentCommand,
    CampaignCalendarChangedEvent,
    CampaignCalendarData,
)
from .campaign import CampaignLevelChangedEvent, CampaignStateChangedEvent
from .characters import (
    CharacterCreateCommand,
    CharacterHealthChangedEvent,
    CharacterHealthCommand,
    CharacterIdentifierCommand,
    CharacterInspirationChangedEvent,
    CharacterLifecycleData,
    CharacterLifecycleEvent,
    CharacterUpdateCommand,
)
from .combat import (
    CharacterConditionCommand,
    CharacterConditionIdentifierCommand,
    CombatantConditionCommand,
    CombatantConditionIdentifierCommand,
    EncounterCharacterAddCommand,
    EncounterCombatantAddCommand,
    EncounterCombatantIdentifierCommand,
    EncounterCombatantReorderCommand,
    EncounterCombatantUpdateCommand,
    EncounterCurrentCombatantCommand,
    InitiativeTieChoiceCommand,
    PlayerInitiativeRollCommand,
)
from .invitations import (
    CampaignInvitationChangedEvent,
    CampaignInvitationData,
    CampaignMemberData,
    CampaignMembershipChangedEvent,
    CampaignPresenceChangedEvent,
    InvitationCreateCommand,
    InvitationIdentifierCommand,
    MemberDeactivationCommand,
)

__all__ = [
    "CalendarAdjustmentCommand",
    "CampaignCalendarChangedEvent",
    "CampaignCalendarData",
    "CampaignInvitationChangedEvent",
    "CampaignInvitationData",
    "CampaignLevelChangedEvent",
    "CampaignMemberData",
    "CampaignMembershipChangedEvent",
    "CampaignPresenceChangedEvent",
    "CampaignStateChangedEvent",
    "CharacterConditionCommand",
    "CharacterConditionIdentifierCommand",
    "CombatantConditionCommand",
    "CombatantConditionIdentifierCommand",
    "CharacterHealthChangedEvent",
    "CharacterHealthCommand",
    "CharacterCreateCommand",
    "CharacterIdentifierCommand",
    "CharacterInspirationChangedEvent",
    "CharacterLifecycleData",
    "CharacterLifecycleEvent",
    "CharacterUpdateCommand",
    "EncounterCharacterAddCommand",
    "EncounterCombatantAddCommand",
    "EncounterCombatantIdentifierCommand",
    "EncounterCombatantReorderCommand",
    "EncounterCombatantUpdateCommand",
    "EncounterCurrentCombatantCommand",
    "InitiativeTieChoiceCommand",
    "PlayerInitiativeRollCommand",
    "InvitationCreateCommand",
    "InvitationIdentifierCommand",
    "MemberDeactivationCommand",
]
