# Generated by Django 6.1 on 2026-08-23 01:16

import django.db.models.deletion
from django.db import migrations, models


def seed_default_repository(apps, schema_editor):
    apps.get_model("compendium", "CompendiumRepository").objects.get_or_create(
        identifier="default",
        defaults={
            "name": "default",
        },
    )


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("campaigns", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompendiumRepository",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("identifier", models.CharField(max_length=200, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("repository_url", models.URLField(blank=True)),
                ("github_repository", models.CharField(blank=True, max_length=300)),
                ("data", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compendium_repositories",
                        to="campaigns.campaign",
                    ),
                ),
            ],
            options={
                "ordering": ("name", "identifier"),
            },
        ),
        migrations.CreateModel(
            name="CompendiumSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("identifier", models.CharField(max_length=200)),
                ("name", models.CharField(max_length=200)),
                ("data", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "repository",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sources",
                        to="compendium.compendiumrepository",
                    ),
                ),
            ],
            options={
                "ordering": ("name", "identifier"),
            },
        ),
        migrations.CreateModel(
            name="CompendiumEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("item", "Item"),
                            ("weapon", "Weapon"),
                            ("armor", "Armor"),
                            ("spell", "Spell"),
                            ("feat", "Feat"),
                            ("class", "Class"),
                            ("race", "Race"),
                            ("background", "Background"),
                            ("monster", "Monster"),
                        ],
                        max_length=20,
                    ),
                ),
                ("source_identifier", models.CharField(max_length=200)),
                ("name", models.CharField(max_length=200)),
                ("source_book", models.CharField(blank=True, max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "cost_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("cost_currency", models.CharField(blank=True, max_length=3)),
                (
                    "weight_amount",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
                ("weight_unit", models.CharField(blank=True, max_length=20)),
                ("rarity", models.CharField(blank=True, max_length=50)),
                ("is_magic", models.BooleanField(blank=True, null=True)),
                ("requires_attunement", models.BooleanField(blank=True, null=True)),
                ("data", models.JSONField(default=dict)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_compendium_entries",
                        to="campaigns.campaigncontext",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="compendium.compendiumsource",
                    ),
                ),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.AddConstraint(
            model_name="compendiumsource",
            constraint=models.UniqueConstraint(
                fields=("repository", "identifier"),
                name="unique_compendium_source_repository_identifier",
            ),
        ),
        migrations.AddIndex(
            model_name="compendiumentry",
            index=models.Index(
                fields=["source", "kind", "name"], name="compendium__source__74c60f_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="compendiumentry",
            constraint=models.UniqueConstraint(
                fields=("source", "kind", "source_identifier"),
                name="unique_compendium_entry_source",
            ),
        ),
        migrations.RunPython(seed_default_repository, migrations.RunPython.noop),
    ]
